### ISSUE TITLE
Dockerfile / requirements path

### ISSUE THREAD

**Issue by demonno** [metakermit/generator-django-rest#1]
There is a small issue with docker file. Line 6 fails because path to requirements file is not correct.

https://github.com/metakermit/generator-django-rest/blob/f0965517a8abe82e41231f0d962644888af4d48c/generators/app/templates/django/mysite/Dockerfile#L5-L6

> Step 6/7 : RUN pip install -r requirements/dev.txt
>  ---> Running in b4af27b5bab2
> Could not open requirements file: [Errno 2] No such file or directory: 'requirements/dev.txt'
> ERROR: Service 'web' failed to build: The command '/bin/sh -c pip install -r requirements/dev.txt' returned a non-zero code: 1

I have tried to change Line 5 like this, which fixed the issue.

```
ADD requirements* /code/requirements/
```

---
[generator-django-rest](https://github.com/metakermit/generator-django-rest) - is awesome, thanks 🎉👏

**Comment by metakermit** [comment]
Cool, glad you like it @demonno! I've merged your PR. Honestly, haven't been using docker-compose myself – mostly running it "on bare metal" 😈 , but nice to hear it's working for you.
