### ISSUE TITLE
No HACKING.md

### ISSUE THREAD

**Issue by ohld** [metakermit/generator-django-rest#12]
At the bottom of the Readme.md there is a reference to HACKING.md file. But I can't find it in the repo.

**Comment by metakermit** [comment]
Hi @ohld, didn't the `yo django-rest` command create a HACKING.md file in the folder as well?

<img width="915" alt="screenshot 2018-08-08 11 15 37" src="https://user-images.githubusercontent.com/1818628/43828322-7bfbd766-9afc-11e8-9bf5-a4794f70c487.png">

If not, please tell me the version of generator-django-rest you were using.

**Comment by ohld** [comment]
Yes, It appeared in my local folder. But it is not obvious where to find this file on Git. I'll create a pull request with a proper link now.

**Comment by metakermit** [comment]
OK, sure.

Yeah, my reasoning for having these two files separate is that having the development setup in HACKING.md and leaving the README.md for customisation makes it easier if you later want to upgrade the project to a newer version of generator-django-rest. Yeoman has some pretty nice CLI tools for diff-ing files and choosing which ones to overwrite (so you would for example overwrite HACKING.md, but keep README.md as it was).

**Comment by ohld** [comment]
That is strange to have the reference to HACKING.md file without the actual link to it.
